version: '3' # 設定ファイルの文法のバージョン３を利用する。

services:

  # 1. phpモジュールを搭載したapacheをインストールするコンテナ。
  php:
    container_name: php

    # phpディレクトリのDockerfileに基づいてコンテナ作成
    build: ./php

    # ホストのhtmlディレクトリをphpコンテナのドキュメントルートと同期。
    volumes: 
        - /c/Users/eiji_yamamoto/MyDocker/lamp_for_codecamp/www:/var/www

    # ホストの8080番ポートをコンテナの80番ポートにフォワード（転送）
    ports: 
        - 8080:80

    # このコンテナはmysqlコンテナに依存する
    depends_on: 
        - mysql

  # 2. mysqlをインストールするコンテナ
  mysql:
    container_name: mysql

    # mysql5.7の公式イメージをそのまま利用。
    image: mysql:5.7

    # mysqlの起動時に文字コードを指定
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0

    # ホストOSのdbフォルダ内にmysqlコンテナのDBの内容を保存
    volumes: 
        - /c/Users/eiji_yamamoto/MyDocker/lamp_for_codecamp/db:/var/lib/mysql

    environment: 
    # mysqlのルートパスワードを設定(環境変数名MYSQL_ROOT_PASSWORD)
        - MYSQL_ROOT_PASSWORD=root

    # デフォルトで作成するデータベース名を設定(環境変数名MYSQL_DATABASE)
        - MYSQL_DATABASE=default_db

    # デフォルトで作成するDBユーザー名を設定(環境変数名MYSQL_USER)
        - MYSQL_USER=db_user

    # デフォルトで作成するDBユーザーのパスワードを設定(環境変数名MYSQL_PASSWORD)
        - MYSQL_PASSWORD=db_user

    # タイムゾーンをAsia/Tokyoに設定(環境変数名TZ)
        - TZ=Asia/Tokyo

  # 3. phpmyadminをインストールするコンテナ
  phpmyadmin:
    container_name: phpmyadmin

    # phpmyadmin/phpmyadminのコンテナイメージをそのまま利用
    image: phpmyadmin/phpmyadmin

    # 接続先DBホストをmysqlコンテナに接続(環境変数名PMA_HOST)
    environment: 
        - PMA_HOST=mysql

    # mysqlコンテナに依存する
    depends_on: 
        - mysql

    # ホストの8888番ポートをphpmyadminコンテナの80番ポートに転送
    ports: 
        - 8888:80